---
- hosts: masters,workers
  become: yes
  tasks:
    - name: Check if kubelet service is running
      systemd:
        name: kubelet
        state: started
      register: kubelet_status

    - name: Print kubelet service status
      debug:
        var: kubelet_status

    - name: Check kubeadm version
      command: kubeadm version
      register: kubeadm_version
      ignore_errors: yes

    - name: Print kubeadm version
      debug:
        var: kubeadm_version.stdout

    - name: Check kubectl version
      command: kubectl version --client=true
      register: kubectl_version
      ignore_errors: yes

    - name: Print kubectl version
      debug:
        var: kubectl_version.stdout

    - name: Check kubelet version
      command: kubelet --version
      register: kubelet_version
      ignore_errors: yes

    - name: Print kubelet version
      debug:
        var: kubelet_version.stdout

- hosts: masters
  become: yes
  tasks:
    - name: Check kubectl get nodes
      command: kubectl get nodes
      register: nodes_output
      ignore_errors: yes

    - name: Print kubectl get nodes output
      debug:
        var: nodes_output.stdout

    - name: Check kubectl get pods -A
      command: kubectl get pods -A
      register: pods_output
      ignore_errors: yes

    - name: Print kubectl get pods -A output
      debug:
        var: pods_output.stdout
